import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fs from 'fs'
import * as path from 'path'
import matter from 'gray-matter'

export interface PostsType {
  frontMatter: {
    [key: string]: any;
  };
  slug: string;
}

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stephen's Development Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet"></link>
      </Head>
      <p>Da hom page</p>
    </div>
  )
}

export default Home

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('blog-posts'))

  const posts = files.map(filename => {
    const markdownWithMeta = fs.readFileSync(path.join('blog-posts', filename))
    const { data: frontMatter } = matter(markdownWithMeta)
    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })

  return {
    props: {
      posts
    }
  }
}